### ISSUE TITLE
Run Spark’s history server

### ISSUE THREAD

**Issue by trunet** [big-data-europe/docker-spark#28]
Create an image to run spark history server.

**Comment by xuexuemiao** [comment]
You may do something like this:

**Comment by trunet** [comment]
This is what I'm doing with extra environment and parameters. However this ticket was opened so a wrapper startup script could be wrote as the other components(master, worker, ...).

**Comment by pwyoung** [comment]
I made a PR to add a Spark History Server. Details are here https://github.com/pwyoung/docker-spark/commit/bfc9d9ddea89524563b93619541d6d4cf634f6fb . Please let me know if there's interest in this.

**Comment by GezimSejdiu** [comment]
Hey @trunet , 

thanks a lot for opening this feature request issue. 

Indeed, spark-history server is quite beneficial in case you want to also view the completed jobs history submitted to Spark.

It was on my TODOs :) and I did add it to my calendar. While trying to implement it saw this message from @pwyoung that he already did have a working setup. 

@pwyoung  -- please feel free to push your contributions here so that I can also review and merge it. Everyone within this thread, please feel free to also comment on the PR so that we all are aligned with the way spark-history-server is setup.

b.t.w @pwyoung I also had in plan to separate it from the spark-master so that it gives us the possibility to use it only when needed, so go ahead as you already did.

Best regards,
