### ISSUE TITLE
Spark error

### ISSUE THREAD

**Issue by gioargyr** [big-data-europe/docker-spark#4]
Hi! I submitted a spark-job in the docker-spark-cluster where the spark-master was bde2020/spark-master:1.5.1-hadoop2.6 and spark-worker(s) were bde2020/spark-worker:1.5.1-hadoop2.6
I got an error that I believe is spark-related ("You need to install libgfortran3."). Is this an error that is resolved  by the newer version or is it something new?
I attached the error, so you can see it whole.
[error.txt](https://github.com/big-data-europe/docker-spark/files/403406/error.txt)

**Comment by erikap** [comment]
Hi @gioargyr, I suppose libgfortran3 is a library required by your Spark application. For now, I would extend the spark-worker docker an install the library in it. We need to come up with a more general approach to tackle this in the future. Otherwise we will end up with custom workers per Spark application.

**Comment by stasinos** [comment]
@erikap , this does not sound very unattractive. We could write in our best practices an example or two of extending the basic Spark container with specific applications and executing from a local Docker file without going through Docker hub. This should be fairly trivial to explain to somebody who is developing a Spark application in the first place, and it pays off as it makes it easier to deploy and test during development.

**Comment by madnificent** [comment]
We could and should make extending the Spark worker easy as other computations will have similar problems.  However, we should heed for having SC-specific Spark workers, rather than problem-specific Spark workers.  I agree with @erikap in that we need to find a solid solution for the broader problem space that comes forth from this issue.

SC specific workers would make the pipeline and its components harder to maintain.  Problem-specific workers could make the pipeline harder to schedule.  For this last approach, dynamic scheduling -- increasing the Spark workers from the workflow -- could be a highly valued feature.  This could be helpful for other larger pipelines also.  However, simpler alternatives may exist.  We should study the implications and find maintainable solutions for customising the workers and other Big Data executors.

We will try to study this approach and see if there's an ideal path which we can follow.  Up 'till then, I too suggest to extend the Spark worker with the libraries you need, and clearly document for which processing steps the extensions are necessary.

**Comment by gioargyr** [comment]
Hi all! Did you extend the Spark-worker? Is there any new version of docker-spark-worker that has the libgfortran3 installed?

**Comment by erikap** [comment]
Hi @gioargyr, I created an extended Spark worker on [the BDE GitHub](https://github.com/big-data-europe/pilot-sc7-spark-worker) that has the `libgfortran3` installed. The Docker image is published on [DockerHub](https://hub.docker.com/r/bde2020/pilot-sc7-spark-worker/). If additional libraries need to be installed, you can just add them in the [Dockerfile](https://github.com/big-data-europe/pilot-sc7-spark-worker/blob/master/Dockerfile).
