### ISSUE TITLE
Spark images (master and worker) no longer build.

### ISSUE THREAD

**Issue by idcrosby** [big-data-europe/docker-spark#65]
The hadoop base image (https://hub.docker.com/r/bde2020/hadoop-base/dockerfile) installs `jessie-backports` which has recently been removed (https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html). So the Docker image no longer builds, nor do any other images which depend on it (including the docker-spark images).

**Comment by idcrosby** [comment]
cc @GezimSejdiu are you seeing the same issues as we are regarding building the image?

**Comment by gmouchakis** [comment]
@idcrosby the base image is alpine but you still see debian in dockehub because there was a build error and the image was not updated. There is an open pull request to fix build issues  (https://github.com/big-data-europe/docker-spark/issues/67) and you can use that to build your images but i'll merge it soon.

**Comment by idcrosby** [comment]
@gmouchakis that's great! I was wondering why it seemed to be alpine in the repo, but not on Docker Hub. Thanks for the update, I'll look out for the new image (and close this issue).
